// examples/vue-ts/src/App.vue
<script setup lang="ts">
import { ref } from 'vue'
import algosdk from 'algosdk'
import { useWallet } from '@txnlab/use-wallet-vue'

const { wallets, activeAddress, signTransactions } = useWallet()

const signedHex = ref<string | null>(null)
const error = ref<string | null>(null)

async function handleConnect() {
  error.value = null
  try {
    const evmWallet = wallets.value[0]
    await evmWallet.connect()
    evmWallet.setActive()
  } catch (err) {
    error.value = err instanceof Error ? err.message : String(err)
  }
}

async function handleDisconnect() {
  signedHex.value = null
  error.value = null
  await wallets.value[0].disconnect()
}

async function handleSign() {
  error.value = null
  signedHex.value = null
  const sender = activeAddress.value
  if (!sender) {
    error.value = 'No active address'
    return
  }
  try {
    const txn = algosdk.makePaymentTxnWithSuggestedParamsFromObject({
      sender,
      receiver: sender,
      amount: 0,
      suggestedParams: {
        fee: 1000,
        minFee: 1000,
        flatFee: true,
        firstValid: 1,
        lastValid: 1000,
        genesisID: 'testnet-v1.0',
        genesisHash: new Uint8Array(32)
      }
    })

    const signed = await signTransactions([txn])
    const blob = signed[0]
    if (!blob) {
      error.value = 'Adapter did not return a signed blob (sender mismatch?)'
      return
    }
    signedHex.value = Array.from(blob, (b) => b.toString(16).padStart(2, '0')).join('')
  } catch (err) {
    error.value = err instanceof Error ? err.message : String(err)
  }
}
</script>

<template>
  <main>
    <h1>use-wallet-xchain-evm — Vue demo</h1>
    <p>
      Connects an EVM wallet (MetaMask et al.), derives an Algorand address via xChain Accounts,
      signs a 0-ALGO self-payment.
    </p>

    <button v-if="!activeAddress" @click="handleConnect">Connect EVM wallet</button>

    <section v-else>
      <h2>Active account</h2>
      <p>
        <strong>Algorand address (derived):</strong>
        <code>{{ activeAddress }}</code>
      </p>
      <button @click="handleSign">Sign test txn</button>
      <button @click="handleDisconnect">Disconnect</button>
    </section>

    <p v-if="error" class="error">Error: {{ error }}</p>

    <section v-if="signedHex">
      <h2>Signed txn (hex)</h2>
      <pre>{{ signedHex }}</pre>
    </section>
  </main>
</template>

<style scoped>
main {
  max-width: 800px;
  margin: 2rem auto;
  padding: 1rem;
  font-family: system-ui, sans-serif;
}
button {
  padding: 0.5rem 1rem;
  margin-right: 0.5rem;
  cursor: pointer;
}
code {
  background: #f4f4f4;
  padding: 0.1rem 0.3rem;
  border-radius: 3px;
  word-break: break-all;
}
pre {
  background: #f4f4f4;
  padding: 1rem;
  overflow-x: auto;
  white-space: pre-wrap;
  word-break: break-all;
}
.error {
  color: #c00;
}
</style>

// examples/react-ts/src/App.tsx
import { useState } from 'react'
import algosdk from 'algosdk'
import { useWallet } from '@txnlab/use-wallet-react'

export function App() {
  const { wallets, activeAddress, signTransactions } = useWallet()
  const evmWallet = wallets[0]

  const [signedHex, setSignedHex] = useState<string | null>(null)
  const [error, setError] = useState<string | null>(null)

  async function handleConnect() {
    setError(null)
    try {
      await evmWallet.connect()
      evmWallet.setActive()
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err))
    }
  }

  async function handleDisconnect() {
    setSignedHex(null)
    setError(null)
    await evmWallet.disconnect()
  }

  async function handleSign() {
    setError(null)
    setSignedHex(null)
    if (!activeAddress) {
      setError('No active address')
      return
    }
    try {
      const txn = algosdk.makePaymentTxnWithSuggestedParamsFromObject({
        sender: activeAddress,
        receiver: activeAddress,
        amount: 0,
        suggestedParams: {
          fee: 1000,
          minFee: 1000,
          flatFee: true,
          firstValid: 1,
          lastValid: 1000,
          genesisID: 'testnet-v1.0',
          genesisHash: new Uint8Array(32)
        }
      })

      const signed = await signTransactions([txn])
      const blob = signed[0]
      if (!blob) {
        setError('Adapter did not return a signed blob (sender mismatch?)')
        return
      }
      setSignedHex(Array.from(blob, (b) => b.toString(16).padStart(2, '0')).join(''))
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err))
    }
  }

  return (
    <main style={{ maxWidth: 800, margin: '2rem auto', padding: '1rem', fontFamily: 'system-ui, sans-serif' }}>
      <h1>use-wallet-xchain-evm — React demo</h1>
      <p>
        Connects an EVM wallet (MetaMask et al.), derives an Algorand address via xChain Accounts,
        signs a 0-ALGO self-payment.
      </p>

      {!activeAddress ? (
        <button onClick={handleConnect}>Connect EVM wallet</button>
      ) : (
        <section>
          <h2>Active account</h2>
          <p>
            <strong>Algorand address (derived):</strong>{' '}
            <code style={{ wordBreak: 'break-all' }}>{activeAddress}</code>
          </p>
          <button onClick={handleSign}>Sign test txn</button>{' '}
          <button onClick={handleDisconnect}>Disconnect</button>
        </section>
      )}

      {error && <p style={{ color: '#c00' }}>Error: {error}</p>}

      {signedHex && (
        <section>
          <h2>Signed txn (hex)</h2>
          <pre style={{ background: '#f4f4f4', padding: '1rem', overflowX: 'auto', whiteSpace: 'pre-wrap', wordBreak: 'break-all' }}>
            {signedHex}
          </pre>
        </section>
      )}
    </main>
  )
}
